services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: wow-much-secret
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql
      - ./scripts:/var/run/scripts
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  metabase:
    image: metabase/metabase:v0.42.2
    restart: always
    ports:
      - 3001:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase:/metabase-data

volumes:
  postgres:
  metabase:
