version: '3.9'

services:
  postgres-service:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql
      - ./scripts:/var/run/scripts
    secrets:
      - postgres-password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  metabase:
    depends_on:
      - postgres-service
    build:
      context: .
      dockerfile: metabase-arm.dockerfile
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS_FILE: /run/secrets/postgres-password
      MB_DB_HOST: postgres-service
    ports:
      - 3001:3000
    secrets:
      - postgres-password

volumes:
  postgres:

secrets:
  postgres-password:
    file: postgres-password.txt
